version: '2'
services:
  sogeBot:
    restart: always
    image: sogebot/release
    ports:
    - "20000:20000/udp"
    - "20443:20443/tcp"
    - "9229:9229/tcp"
    volumes:
    - /srv/docker/bind:/data
    environment:
    - ROOT_PASSWORD=changeme
    mariadb:
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: password
